name: Development Workflow

on:
  pull_request:
    branches: 
      - master

jobs:
  DeployOnDev:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16.x
        uses: actions/checkout@v2
        with:
          node-version: 16.x

      # - name: Trigger Smoke Test Dev
      #   uses: convictional/trigger-workflow-and-wait@v1.3.0
      #   with:
      #     owner: eyblockchain
      #     repo: bec-developer-portal
      #     github_token: ${{ secrets.GPR_TOKEN_WITH_WORKFLOW_RIGHT }}
      #     workflow_file_name: smoke_test_dev.yml
      #     ref: master
      #     wait_interval: 10
      #     propagate_failure: true
      #     trigger_workflow: true
      #     wait_workflow: true
      #     inputs:
      #       '{"triggerFromRepo": "${{ github.repository }}", "triggerFromWorkflow": "${{
      #       github.workflow }}", "triggerFromRunId": "${{ github.run_id }}", "triggerFromCommitSHA":
      #       "${{ github.sha }}"}'

      # API Endpoints Integration tests
      # - name: Prepare Newman-Postman Integration Environment and Scripts for Tokenization
      #   if: "!contains(steps.commit_msg.outputs.message, 'skip e2e test')"
      #   env:
      #     COMMIT_SHA: ${{ github.sha }}
      #     PR_NUMBER: ${{ github.event.number }}
      #     PARTNER_WALLET: '0x65cE0Eb84cf88d1c33DF5474f1aa2F901819835E'
      #   run: |
      #     sed -i -- "s/{{prNumber}}/$PR_NUMBER/" ./tests/envs/dev/tokenization/*
      #     sed -i -- "s/{{CI_CD_Contract_Name}}/$COMMIT_SHA/" ./tests/collections/tokenization/*
      #     sed -i -- "s/{{PartnerWalletAddress_Param}}/$PARTNER_WALLET/" ./tests/collections/tokenization/*

      # - name: Execute Newman-Postman Integration Test for Tokenization
      #   if: "!contains(steps.commit_msg.outputs.message, 'skip e2e test')"
      #   run: |
      #     newman run "./postman/collections/API-Gateway-ERC721-Regression-Tests.postman_collection.json" --environment "./postman/envs/dev/Developer-portal-dev.postman_environment.json" --insecure
