#name: Release to Dev Environment
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  release:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: semantic release
#        uses: codfish/semantic-release-action@v1
#        id: semantic
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Trigger Smoke Test Dev
#        uses: convictional/trigger-workflow-and-wait@v1.3.0
#        with:
#          owner: eyblockchain
#          repo: bec-developer-portal
#          github_token: ${{ secrets.GPR_TOKEN_WITH_WORKFLOW_RIGHT }}
#          workflow_file_name: smoke_test_dev.yml
#          ref: master
#          wait_interval: 10
#          propagate_failure: true
#          trigger_workflow: true
#          wait_workflow: true
#          inputs:
#            '{"triggerFromRepo": "${{ github.repository }}", "triggerFromWorkflow": "${{
#            github.workflow }}", "triggerFromRunId": "${{ github.run_id }}", "triggerFromCommitSHA":
#            "${{ github.sha }}"}'
#
#      # - name: Send slack notification to bec-failure-notifications channel
#      #   uses: 8398a7/action-slack@v3.11.0
#      #   with:
#      #     status: ${{ job.status }}
#      #     fields: author,repo,workflow,message,commit,action,eventName,ref,pullRequest,job,took
#      #   env:
#      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_BEC_FAILURE_NOTIFICATION_CHANNEL }}
#      #   if: ${{ always() && job.status == 'failure' }}

name: Release to Dev Environment

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout action
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: validate before release
        run: |
          npm ci --no-save
        env:
          SKIP_PREFLIGHT_CHECK: true
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
          CI: true

      - name: semantic release
        uses: ahmadnassri/action-semantic-release@v1.7.2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
