name: Smoke Test - Stage

on:
  workflow_dispatch:
    inputs:
      triggerFromRepo:
        description: 'This workflow is triggered from which repo'
        required: true
        default: 'From another repo'
      triggerFromWorkflow:
        description: 'Workflow name in triggering repo'
        required: true
        default: 'From workflow name'
      triggerFromRunId:
        description: 'Run_id in triggering repo'
        required: true
        default: 'Run_id'
      triggerFromCommitSHA:
        description: 'Commit SHA in triggering repo'
        required: true
        default: 'Commit SHA'

jobs:
  cypress-run-on-stage:
    runs-on: ubuntu-latest
    name: Cypress Run
    steps:
      - uses: actions/checkout@v2

      - name: print inputs from calling workflow
        run: |
          echo "Trigger From Repo: ${{ github.event.inputs.triggerFromRepo }}"
          echo "Trigger From Workflow: ${{ github.event.inputs.triggerFromWorkflow }}"
          echo "Trigger From RunId: ${{ github.event.inputs.triggerFromRunId }}"
          echo "Trigger From Commit SHA: ${{ github.event.inputs.triggerFromCommitSHA }}"

      - name: Run Smoke Tests
        uses: cypress-io/github-action@v2
        id: cypress_smoke_test
        with:
          browser: chrome
          spec: |
            ./cypress/integration/api_management_portal.spec.js
        env:
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
          CYPRESS_baseUrl: https://developer-portal-stage.blockchain.ey.com
         CYPRESS_email: "test.blockchain.ey@gmail.com"
          CYPRESS_password: "manaf@123"

      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

  postman-run-on-stage:
    runs-on: ubuntu-latest
    name: Postman Run
    steps:
      - uses: actions/checkout@v2

      - name: print inputs from calling workflow
        run: |
          echo "Trigger From Repo: ${{ github.event.inputs.triggerFromRepo }}"
          echo "Trigger From Workflow: ${{ github.event.inputs.triggerFromWorkflow }}"
          echo "Trigger From RunId: ${{ github.event.inputs.triggerFromRunId }}"
          echo "Trigger From Commit SHA: ${{ github.event.inputs.triggerFromCommitSHA }}"

      - name: Prepare Newman-Postman Integration Environment and Scripts for Tokenization
        if: "!contains(steps.commit_msg.outputs.message, 'skip e2e test')"
        env:
          DEVELOPER_PORTAL_URL: 'https:\/\/developer-portal-stage.blockchain.ey.com\/opschain-tokenization'
          CLIENT_ID: '628f4220cd44b890b0a61a09'
          CLIENT_SECRET: 'd4aaa5d7-9639-4c96-8b8e-fdab5ec30a0d'
          CLIENT_ID2: '628f4250cd44b890b0a61a0a'
          CLIENT_SECRET2: '6e578743-6220-46c8-8b41-58174d6f370c'
          SUBSCRIPTION_KEY: 'b807209b444c4e14916a66a3962ad27f'
          PARTNER_WALLET: '0x0a6BbBCA59e3E992ea47C1ea9b67f6c922B3020e'
        run: |
          sed -i -- "s/{{clientID}}/$CLIENT_ID/" ./postman/envs/Developer-portal.postman_environment.json
          sed -i -- "s/{{clientSecret}}/$CLIENT_SECRET/" ./postman/envs/Developer-portal.postman_environment.json
          sed -i -- "s/{{clientID2}}/$CLIENT_ID2/" ./postman/envs/Developer-portal.postman_environment.json
          sed -i -- "s/{{clientSecret2}}/$CLIENT_SECRET2/" ./postman/envs/Developer-portal.postman_environment.json
          sed -i -- "s/{{subscriptionKey}}/$SUBSCRIPTION_KEY/" ./postman/envs/Developer-portal.postman_environment.json
          sed -i -- "s/{{partnerWallet}}/$PARTNER_WALLET/" ./postman/envs/Developer-portal.postman_environment.json
          sed -i -- "s/{{developerPortalUrl}}/$DEVELOPER_PORTAL_URL/" ./postman/envs/Developer-portal.postman_environment.json

      - name: Execute Newman-Postman Integration Test for Tokenization
        if: "!contains(steps.commit_msg.outputs.message, 'skip e2e test')"
        run: |
          newman run "./postman/collections/API-Gateway-ERC721-Regression-Tests.postman_collection.json" --environment "./postman/envs/Developer-portal.postman_environment.json" --insecure